name: Hello Name Workflow

on:
  workflow_dispatch:
    inputs:
      my_name:
        description: "Enter your name"
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: |
          echo "Hello ${{ inputs.my_name }}"