name: Artifact Demo

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  
jobs:

  create-artifact:
    runs-on: ubuntu-latest
    steps:
       
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Upload entire repo as artifact
         uses: actions/upload-artifact@v4
         with:
          name: my-repo-zip
          path: .

  verify-artifact:
    needs: create-artifact
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-repo-zip
          path: downloaded-repo
      - name: List extracted files
        run: |
          cd downloaded-repo
          echo "Here are all the files in the artifact:"
          ls -laR  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::116912494636:role/github-IAMRole-assume-policy
          aws-region: us-east-2
          role-session-name: gha-${{ github.run_id }}
      - name: Upload to S3
        run: |
            aws s3 cp ./to-upload s3://githud-artifact-upload-s3/${{ github.run_id }}/ --recursive
